# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ee00d115fd6654176f59a8c7175b2ffce5957d874d767ce33056ea08e4dd19ea63d430133155ecb64e701e91794bb2c762df62e5c5172e5cd258b6faf76b22d

test:
  secret_key_base: f79a3fa88a966e4e91184a855d7129aad874ae2729ca040810a1c7d21065792facd6d39d42c12bcce6b3cbec46e9b5f7168bb853c88805407dc469a1896c76e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
